// MIT License
// Copyright (c) 2026 Dennis B Jones
//
// Integration: the Phase 1 exit test. CLI-shaped flow, in-process:
// ServiceManager spawns savannahd over pipes, savannahd spawns fake-claude,
// chunks stream back typed, RESULT trailer terminates. Zero tokens.
//
// Also covers: tool events, bad-json resilience, die-before-result synthesis,
// timeout via the hang scenario, and status/info/cancel unary calls.
//
// Requires cwd = build dir (ctest sets WORKING_DIRECTORY) with ./savannahd,
// ./fake-claude, and the scenario configs generated by CMake.

#include <song/song.hpp>

#include <cstdio>
#include <cstdlib>
#include <string>
#include <vector>

#include "savannah.hpp"
#include "../src/wire_ids.hpp"
#include "../src/stream_json.hpp"

namespace sw = song::savannah;
using song::Buffer;
using song::ServiceConnection;
using song::ServiceManager;
using song::u32;

static int g_failures = 0;

#define CHECK(cond)                                                     \
    do {                                                                \
        if (!(cond)) {                                                  \
            std::printf("FAIL %s:%d: %s\n", __FILE__, __LINE__, #cond); \
            ++g_failures;                                               \
        }                                                               \
    } while (0)

namespace {

struct Streamed {
    std::string text;
    std::vector<std::string> tools;
    std::string result;
    int chunk_count = 0;
    std::size_t max_payload = 0;
};

Streamed ask(ServiceConnection& conn, const std::string& prompt,
             u32 timeout_ms = 0) {
    sw::AskOptions opts;
    opts.timeout_ms = timeout_ms;
    opts.fresh_context = true;
    opts.system_hint = "";

    Buffer args;
    song::encode_string(args, prompt);
    sw::encode_AskOptions(args, opts);

    auto reader = conn.call_streaming(
        savannah_wire::kService_AgentNode_Stream,
        sw::kMethod_AgentNode_ask, args);
    Streamed out;
    while (reader.next()) {
        auto c = sw::decode_AgentChunk(reader.chunk());
        ++out.chunk_count;
        if (c.payload.size() > out.max_payload) out.max_payload = c.payload.size();
        switch (c.kind) {
            case 0: out.text += c.payload; break;
            case 1: out.tools.push_back(c.payload); break;
            case 2: out.result = c.payload; break;
            default: break;
        }
    }
    return out;
}

ServiceConnection connect_with_config(ServiceManager& mgr,
                                      const char* config,
                                      const char* name) {
    setenv("SAVANNAHD_CONFIG", config, 1);
    mgr.register_service(name, "./savannahd", 1);
    return mgr.connect(name);
}

}  // namespace

int main() {
    // Wire kind values are pinned by the IDL comment: 0 TEXT, 1 TOOL_EVENT,
    // 2 RESULT. savannahd casts the internal enum through int; keep aligned.
    static_assert(static_cast<int>(savannah::ChunkKind::Text) == 0);
    static_assert(static_cast<int>(savannah::ChunkKind::ToolEvent) == 1);
    static_assert(static_cast<int>(savannah::ChunkKind::Result) == 2);

    // ---- echo: the Phase 1 exit test ----
    {
        ServiceManager mgr;
        auto conn = connect_with_config(mgr, "cfg_echo.toml", "echo");
        auto r = ask(conn, "hello savannah");
        CHECK(r.text == "hello savannah");
        CHECK(r.result.find("\"is_error\":false") != std::string::npos);
        CHECK(r.result.find("\"cost_usd\":0.00042") != std::string::npos);
        CHECK(r.tools.empty());

        // info/status on the same connection.
        Buffer req;
        Buffer resp = conn.call(sw::kService_AgentNode,
                                sw::kMethod_AgentNode_info, req);
        auto info = sw::decode_AgentInfo(resp);
        CHECK(info.name == "echo-node");
        CHECK(info.protocol_ver == 1);
        CHECK(info.tags.size() == 2);

        Buffer req2;
        Buffer resp2 = conn.call(sw::kService_AgentNode,
                                 sw::kMethod_AgentNode_status, req2);
        CHECK(song::decode_string(resp2) == "idle");

        // cancel with nothing in flight: false.
        Buffer req3;
        Buffer resp3 = conn.call(sw::kService_AgentNode,
                                 sw::kMethod_AgentNode_cancel, req3);
        CHECK(song::decode_bool(resp3) == false);

        // Second ask on the same node: single-flight state resets cleanly.
        auto r2 = ask(conn, "again");
        CHECK(r2.text == "again");
    }

    // ---- tool storm: TOOL_EVENT chunks arrive typed ----
    {
        ServiceManager mgr;
        auto conn = connect_with_config(mgr, "cfg_tools.toml", "tools");
        auto r = ask(conn, "do things");
        CHECK(r.tools.size() == 3);
        CHECK(r.tools[0].rfind("Bash: git status", 0) == 0);
        CHECK(r.text.find("storm complete") != std::string::npos);
        CHECK(r.result.find("\"is_error\":false") != std::string::npos);
    }

    // ---- bad json between valid lines: skipped, not fatal ----
    {
        ServiceManager mgr;
        auto conn = connect_with_config(mgr, "cfg_badjson.toml", "bad");
        auto r = ask(conn, "resilience");
        CHECK(r.text.find("valid before garbage") != std::string::npos);
        CHECK(r.text.find("valid after garbage") != std::string::npos);
        CHECK(r.result.find("\"is_error\":false") != std::string::npos);
    }

    // ---- giant chunk: a 4 MiB text block survives the line pump and the
    //      wire intact. song's encode_string caps at 1 MB, so savannahd must
    //      split it: 8 TEXT chunks of 512 KiB, then the RESULT trailer. ----
    {
        constexpr std::size_t kGiant = 4194304;    // matches cfg_giant.toml
        constexpr std::size_t kSplit = 512 * 1024; // savannahd kMaxChunkPayload
        ServiceManager mgr;
        auto conn = connect_with_config(mgr, "cfg_giant.toml", "giant");
        auto r = ask(conn, "big");
        CHECK(r.text.size() == kGiant);
        CHECK(r.text.find_first_not_of('x') == std::string::npos);
        CHECK(r.chunk_count == static_cast<int>(kGiant / kSplit) + 1);
        CHECK(r.max_payload <= kSplit);
        CHECK(r.result.find("\"is_error\":false") != std::string::npos);
    }

    // ---- slow drip: 6 chunks with 150ms gaps (past the 100ms poll tick).
    //      Neither the agent pump nor the stream client may give up between
    //      chunks, and nothing may coalesce or drop. ----
    {
        ServiceManager mgr;
        auto conn = connect_with_config(mgr, "cfg_drip.toml", "drip");
        const std::string prompt = "abcdefghijklmnopqrstuvwx";  // 24 = 6 * 4
        auto r = ask(conn, prompt);
        CHECK(r.text == prompt);
        CHECK(r.chunk_count == 7);  // 6 TEXT + 1 RESULT
        CHECK(r.result.find("\"is_error\":false") != std::string::npos);
    }

    // ---- mid-UTF8 splits: a line split across pipe writes inside a 4-byte
    //      codepoint, then a text block split across TEXT chunks inside a
    //      2-byte codepoint. Concatenated text must be byte-identical. ----
    {
        ServiceManager mgr;
        auto conn = connect_with_config(mgr, "cfg_utf8.toml", "utf8");
        auto r = ask(conn, "unicode");
        const std::string expected =
            "roar \xF0\x9F\xA6\x81 savanna \xC3\xA9l\xC3\xA9phant";
        CHECK(r.text == expected);
        CHECK(r.chunk_count == 4);  // 3 TEXT (1 whole + 1 split pair), 1 RESULT
        CHECK(r.result.find("\"is_error\":false") != std::string::npos);
    }

    // ---- agent dies before result: synthetic error trailer ----
    {
        ServiceManager mgr;
        auto conn = connect_with_config(mgr, "cfg_die.toml", "die");
        auto r = ask(conn, "doomed");
        CHECK(r.result.find("\"is_error\":true") != std::string::npos);
        CHECK(r.result.find("died before result") != std::string::npos);
        CHECK(r.result.find("\"exit_code\":3") != std::string::npos);
    }

    // ---- hang + short ask timeout: timeout trailer, node stays usable ----
    {
        ServiceManager mgr;
        auto conn = connect_with_config(mgr, "cfg_hang.toml", "hang");
        auto r = ask(conn, "never", /*timeout_ms=*/500);
        CHECK(r.result.find("\"is_error\":true") != std::string::npos);
        CHECK(r.result.find("timeout") != std::string::npos);

        Buffer req;
        Buffer resp = conn.call(sw::kService_AgentNode,
                                sw::kMethod_AgentNode_status, req);
        CHECK(song::decode_string(resp) == "idle");  // flight cleared after timeout
    }

    if (g_failures == 0) std::printf("test_integration_echo: all passed\n");
    return g_failures == 0 ? 0 : 1;
}
