// MIT License
// Copyright (c) 2026 Dennis B Jones
//
// Integration: HMAC-authenticated TCP serving. Loopback only, CI-safe, no
// mDNS involved. Three postures against a keyed savannahd:
//   right key  -> full ask/info round-trip works
//   wrong key  -> rejected at the handshake (tag mismatch)
//   no key     -> rejected before any dispatcher runs
//
// Requires cwd = build dir with ./savannahd, ./fake-claude, cfg_secure.toml,
// test.key, and test_wrong.key (all generated by CMake).

#include <song/song.hpp>
#include <song/security.hpp>

#include <signal.h>
#include <sys/wait.h>
#include <unistd.h>

#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <memory>
#include <string>

#include "savannah.hpp"
#include "../src/config.hpp"
#include "../src/wire_ids.hpp"

namespace sw = song::savannah;
using song::Buffer;
using song::ServiceConnection;
using song::u16;

static int g_failures = 0;

#define CHECK(cond)                                                     \
    do {                                                                \
        if (!(cond)) {                                                  \
            std::printf("FAIL %s:%d: %s\n", __FILE__, __LINE__, #cond); \
            ++g_failures;                                               \
        }                                                               \
    } while (0)

namespace {

struct Daemon {
    pid_t pid = -1;
    u16 port = 0;

    static Daemon spawn(const char* config) {
        Daemon d;
        int fds[2];
        if (pipe(fds) != 0) return d;
        pid_t pid = fork();
        if (pid < 0) {
            close(fds[0]);
            close(fds[1]);
            return d;
        }
        if (pid == 0) {
            dup2(fds[1], STDOUT_FILENO);
            close(fds[0]);
            close(fds[1]);
            setenv("SAVANNAHD_CONFIG", config, 1);
            execl("./savannahd", "savannahd", "--tcp", "0",
                  static_cast<char*>(nullptr));
            _exit(127);
        }
        close(fds[1]);
        std::string line;
        char c;
        while (read(fds[0], &c, 1) == 1 && c != '\n') line.push_back(c);
        close(fds[0]);
        const char* marker = "SAVANNAHD_TCP_PORT=";
        if (line.rfind(marker, 0) == 0) {
            d.pid = pid;
            d.port = static_cast<u16>(
                std::strtoul(line.c_str() + std::strlen(marker), nullptr, 10));
        } else {
            kill(pid, SIGKILL);
            waitpid(pid, nullptr, 0);
        }
        return d;
    }

    ~Daemon() {
        if (pid > 0) {
            kill(pid, SIGKILL);
            waitpid(pid, nullptr, 0);
        }
    }
};

// Connect with an optional HMAC key; empty key = plaintext client.
ServiceConnection connect(u16 port, const std::string& key) {
    auto tcp = std::make_unique<song::TcpTransport>();
    tcp->connect("127.0.0.1", port, 5000);
    std::unique_ptr<song::Transport> transport = std::move(tcp);
    if (!key.empty()) {
        transport = std::make_unique<song::SecureTransport>(
            std::move(transport), song::SecurityConfig(key));
    }
    ServiceConnection conn(std::move(transport));
    conn.init_handshake();
    return conn;
}

std::string ask_text(ServiceConnection& conn, const std::string& prompt) {
    sw::AskOptions opts;
    opts.timeout_ms = 0;
    opts.fresh_context = true;
    opts.system_hint = "";
    Buffer args;
    song::encode_string(args, prompt);
    sw::encode_AskOptions(args, opts);
    auto reader = conn.call_streaming(
        savannah_wire::kService_AgentNode_Stream,
        sw::kMethod_AgentNode_ask, args);
    std::string text;
    bool saw_ok_result = false;
    while (reader.next()) {
        auto c = sw::decode_AgentChunk(reader.chunk());
        if (c.kind == 0) text += c.payload;
        if (c.kind == 2) {
            saw_ok_result =
                c.payload.find("\"is_error\":false") != std::string::npos;
        }
    }
    CHECK(saw_ok_result);
    return text;
}

}  // namespace

int main() {
    const std::string key = savannah::load_hmac_key("test.key");
    const std::string wrong_key = savannah::load_hmac_key("test_wrong.key");

    Daemon d = Daemon::spawn("cfg_secure.toml");
    CHECK(d.pid > 0);
    CHECK(d.port != 0);
    if (g_failures) return 1;

    // ---- right key: everything works over the secured transport ----
    {
        auto conn = connect(d.port, key);
        CHECK(ask_text(conn, "over hmac") == "over hmac");

        Buffer req;
        Buffer resp = conn.call(sw::kService_AgentNode,
                                sw::kMethod_AgentNode_info, req);
        auto info = sw::decode_AgentInfo(resp);
        CHECK(info.name == "secure-node");
    }

    // ---- wrong key: the server's init confirmation fails verification
    //      client-side; nothing usable comes back ----
    {
        bool rejected = false;
        try {
            auto conn = connect(d.port, wrong_key);
            Buffer req;
            conn.call(sw::kService_AgentNode, sw::kMethod_AgentNode_status,
                      req);
        } catch (const std::exception&) {
            rejected = true;
        }
        CHECK(rejected);
    }

    // ---- no key: the server drops the client on its first unauthenticated
    //      message, before any dispatcher runs ----
    {
        bool rejected = false;
        try {
            auto conn = connect(d.port, "");
            Buffer req;
            conn.call(sw::kService_AgentNode, sw::kMethod_AgentNode_status,
                      req);
        } catch (const std::exception&) {
            rejected = true;
        }
        CHECK(rejected);
    }

    // ---- and the node is still healthy for keyed clients afterward ----
    {
        auto conn = connect(d.port, key);
        CHECK(ask_text(conn, "still alive") == "still alive");
    }

    if (g_failures == 0) std::printf("test_secure: all passed\n");
    return g_failures == 0 ? 0 : 1;
}
